version: 0.1
phases:
 pre_build:
  commands:
   - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
   - php composer-setup.php
   - mv composer.phar /usr/local/bin/composer
artifacts:
 files:
  - '**/*'
 name: icy-$(date +%Y-%m-%d)
